POST http://localhost:9200/_aliases
Content-Type: application/json

{
  "actions": [
    {
      "add": {
        "alias": "customer",
        "index": "customers"
      }
    },
    {
      "add": {
        "alias": "order",
        "index": "orders"
      }
    }
  ]
}

### get aliases
GET http://localhost:9200/_aliases

### get customers
GET http://localhost:9200/customers/_search

###
GET http://localhost:9200/order/_search