###
POST http://localhost:9200/categories/_doc/2
Content-Type: application/json

{
  "name": "Salah"
}

###
POST http://localhost:9200/categories/_doc/3
Content-Type: application/json

{
  "name": "Salah Lagi"
}

###
POST http://localhost:9200/categories/_search

### delete 
POST http://localhost:9200/categories/_delete_by_query
Content-Type: application/json

{
  "query": {
    "match": {
      "name": "salah"
    }
  }
}