# Update API
# ● Ketika melakukan update menggunakan Index API, Index API akan melakukan replace, artinya
# dokumen sebelumnya akan dihapus dan dibuat baru, hal ini mengakibatkan kita harus mengirim
# seluruh atributnya lagi, karena jika kita hanya mengirim atribut yang di-update, secara otomatis
# akan ditimpa, artinya data di atribut lain bisa hilang
# ● Jika kita ingin mengupdate beberapa atribut saja di dokumen, tanpa harus mengirim ulang seluruh
# atribut, kita bisa menggunakan Update API dengan RESTful API :
# POST /<index_name>/_update/<id>
# ● Jika dokumen yang di update tidak tersedia, maka Elasticsearch akan mengembalikan 404 Not
# Found

### create product 5
POST http://localhost:9200/products/_doc/5
Content-Type: application/json

{
  "name": "Acer Predator",
  "price": 25000000
}

###
POSt http://localhost:9200/products/_doc/5
Content-Type: application/json

{
  "price": 30000000
}

### 
GET http://localhost:9200/products/_doc/5


### DENGAN UPDATE API
### update price for product 5
POST http://localhost:9200/products/_update/5
Content-Type: application/json

{
  "doc": {
    "price": 30000000
  }
}

###
POST http://localhost:9200/products/_search

###
DELETE http://localhost:9200/products/_doc/MS2g_YwBJTlb9W4kabgQ